In [6]:
import numpy
p = numpy.array([15, 20, 35, 40, 45])
print(p)

[15 20 35 40 45]


In [7]:
 import numpy as np
print(np.__version__)

1.20.1


In [9]:
import numpy as np
p = np.array([15, 25, 35, 45, 55, 60])
print(p)
print(type(p))

[15 25 35 45 55 60]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
i = np.array((10, 20, 30, 40, 50, 60))
print(i)

[10 20 30 40 50 60]
